name:                straightForward
version:             0.1.0.0
github:              "theSeafarer/straightForward"
license:             BSD3
author:              "Parham Zahiri"
maintainer:          "lambdaxmapstox@gmail.com"
copyright:           "2018 Parham Zahiri"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on Github at <https://github.com/theSeafarer/straightForward#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13
- bytestring >= 0.10
- word8
- scientific
- template-haskell >= 2.12

library:
  source-dirs: src


tests:
  straightForward-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - straightForward
    - bytestring
    - smallcheck
    - tasty
    - aeson
    - tasty-hunit
    - tasty-smallcheck
